$domain = "missoula.local"
$domain_ip_address = "192.168.56.2"

Vagrant.configure("2") do |config|
    config.vm.box = "gusztavvargadr/windows-server"
    config.vm.define "windows-dc01"
    config.vm.hostname = "dc01"

    # use the plaintext WinRM transport and force it to use basic authentication.
    # NB this is needed because the default negotiate transport stops working
    #    after the domain controller is installed.
    #    see https://groups.google.com/forum/#!topic/vagrant-up/sZantuCM0q4
    config.winrm.transport = :plaintext
    config.winrm.basic_auth_only = true


    config.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
      vb.name = "dc01"
    end

    config.vm.network "private_network", ip: "192.168.56.2", virtualbox__intnet: "network_os"

    config.vm.provision "shell", path: "provision/ps.ps1", args: ["configure-hyperv-guest.ps1", $domain_ip_address]
    config.vm.provision "shell", path: "provision/ps.ps1", args: ["domain-controller.ps1", $domain]
    config.vm.provision "shell", reboot: true
    config.vm.provision "shell", path: "provision/ps.ps1", args: "domain-controller-wait-for-ready.ps1"
    config.vm.provision "shell", path: "provision/ps.ps1", args: "set-vagrant-domain-admin.ps1"
    config.vm.provision "shell", path: "provision/ps.ps1", args: "domain-controller-configure.ps1"
    config.vm.provision "shell", inline: "$env:chocolateyVersion='0.12.1'; iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex", name: "Install Chocolatey"
    config.vm.provision "shell", path: "provision/ps.ps1", args: "provision-base.ps1"
    config.vm.provision "shell", reboot: true
    config.vm.provision "shell", path: "provision/ps.ps1", args: "domain-controller-wait-for-ready.ps1"
    config.vm.provision "shell", inline: "cd c:/vagrant/provision; ./provision-gpos.ps1"
    config.vm.provision "shell", path: "provision/ps.ps1", args: "ad-explorer.ps1"
    config.vm.provision "shell", reboot: true
    config.vm.provision "shell", inline: <<-SHELL
      Remove-netIpAddress -interfaceAlias "Ethernet 2" -confirm:$false
      new-netipAddress -interfaceAlias "Ethernet 2" -IPAddress 192.168.56.2 -DefaultGateway 192.168.56.1 -PrefixLength 24
    SHELL
    config.vm.provision "shell", path: "provision/ps.ps1", args: "summary.ps1"
end
