Vagrant.configure("2") do |config|
  config.vm.box = "kennyl/pfsense"
  config.vm.box_version = "2.4.0"

  config.vm.network "private_network", ip: "192.168.56.1", virtualbox__intnet: "network_os"
#config.vm.hostname = "pfsense"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
    vb.cpus = 1
    vb.name = "pfsense"
  end

end
