$installvagrant = <<-SCRIPT
sudo apt update
sudo apt-get install ca-certificates curl gnupg lsb-release -y
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin docker-compose -y
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "aspyatkin/ubuntu-18.04-server"
  config.vm.network "private_network", type: "dhcp", virtualbox__intnet: "network_os"
  config.vm.hostname = "linuxserver1"

  config.vm.provider "virtualbox" do |vb|
   vb.memory = 2048
   vb.cpus = 1
   vb.name = "linuxserver1"
 end

  config.vm.provision "shell", inline: $installvagrant
end