# Note - I had to use vbguest versin 0.21 to get the provision script to work
# vagrant plugin install vagrant-vbguest --plugin-version 0.21

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", type: "dhcp", virtualbox__intnet: "network_os"
  config.vm.hostname = "linuxserver1"

  config.vm.provider "virtualbox" do |vb|
   vb.memory = 2048
   vb.cpus = 1
   vb.name = "linuxserver1"
  end

  config.vm.provision :shell, :path => "provision.sh"
end