Vagrant.configure("2") do |config|
  config.vm.box = "aspyatkin/ubuntu-18.04-server"
  config.vm.network "private_network", type: "dhcp", virtualbox__intnet: "network_os"
  config.vm.hostname = "linuxserver1"

  config.vm.provider "virtualbox" do |vb|
   vb.memory = 2048
   vb.cpus = 1
   vb.name = "linuxserver1"
 end
end