# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

 config.vbguest.auto_update = false

 config.vm.box = "gusztavvargadr/windows-server"
 config.vm.network "private_network", type: "dhcp", virtualbox__intnet: "network_os"
 config.vm.hostname = "winServer1"

 config.vm.provider "virtualbox" do |vb|
   vb.memory = 2048
   vb.cpus = 1
   vb.name = "winServer1"
 end
 config.vm.provision "shell", path: "provision/ps.ps1", args: "provision-base.ps1"
 config.vm.provision "shell", inline: <<-SHELL
  $username="Missoula\\vagrant"
  $password=ConvertTo-SecureString -AsPlainText "vagrant" -force
  $creds=new-object system.management.automation.pscredential $username,$password

  # set DNS Server to the domain controller
  Set-DnsClientServerAddress -interfacealias "Ethernet 2" -ServerAddresses ("192.168.56.2")

  #Add this computer to the domain
  add-computer -DomainName "Missoula.local" -Credential $creds -Server dc01 -restart
 SHELL

end 
