# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

 config.vbguest.auto_update = false

 config.vm.box = "gusztavvargadr/windows-server"
 config.vm.network "private_network", type: "dhcp", virtualbox__intnet: "network_os"
 config.vm.hostname = "winServer2"

 config.vm.provider "virtualbox" do |vb|
   vb.memory = 2048
   vb.cpus = 1
   vb.name = "winServer2"
 end
 config.vm.provision "shell", path: "provision/ps.ps1", args: "provision-base.ps1"

end 
